server:
  servlet:
    context-path: /ola-chat
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ola-chat?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb+srv://mongodb:mongopassword@ola-cluster.2db1h.mongodb.net/?retryWrites=true&w=majority&appName=Ola-Cluster
      database: Ola-Cluster
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000

cloudinary:
  cloud_name: dwip7dplu
  api_key: 944366892271352
  api_secret: SGhlTmcznfxn-1T0T8D2BQQOA9Q

jwt:
  signerKey: zhRPPUbgnHMtrH0Fj3reft+wa6HFXDlcwSNbTPEA3cQUdCb4aXANrlQntnH1QAYc
  valid-duration: 3600
  refreshable-duration: 36000