server:
  servlet:
    context-path: /ola-chat
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  tomcat:
        max-http-header-size: 64KB

spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: tieuvy5723@gmail.com
    password: fbjj qdvu xskr xzgv
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: false

  datasource:
#    url: jdbc:mysql://tramway.proxy.rlwy.net:13286/railway
#    username: root
#    password: yzVnFnkUwYqDCCYOFFHREvrCzTRkbswj

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/ola-chat?createDatabaseIfNotExist=true

    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://mongodb:mongopassword@ola-cluster.2db1h.mongodb.net/?retryWrites=true&w=majority&appName=ola-chat-db
      database: ola-chat
#    redis:
#      host: maglev.proxy.rlwy.net
#      port: 30825
#      username: default
#      password: RyTQwEZwwUnrJcNObOxamkGOSwoUnNBl
#      ssl:
#        enabled: true
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000




cloudinary:
  cloud_name: dwip7dplu
  api_key: 944366892271352
  api_secret: SGhlTmcznfxn-1T0T8D2BQQOA9Q

jwt:
  signerKey: zhRPPUbgnHMtrH0Fj3reft+wa6HFXDlcwSNbTPEA3cQUdCb4aXANrlQntnH1QAYc
  valid-duration: 3600
  refreshable-duration: 36000
