spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/olachat?createDatabaseIfNotExist=true
    username: root
    password: sapassword

  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb+srv://root:sapassword@ola-cluster.ybrrl.mongodb.net/?retryWrites=true&w=majority&appName=Ola-Cluster
      database: ola-chat
